version: "3.8"

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web
    environment:
      - DEBUG=1
      - DJANGO_DEVELOPMENT=1
    ports:
      - "8000:8000"

  celery:
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A MoxieApp worker -l info
    environment:
      - DEBUG=1
      - DJANGO_DEVELOPMENT=1

  celery-beat:
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A MoxieApp beat -l info
    environment:
      - DEBUG=1
      - DJANGO_DEVELOPMENT=1
